#!/usr/bin/env python3
"""
generate.py — build data.js from a folder of ALTO XML + image pairs.

Usage:
    python generate.py [EXAMPLES_DIR] [OUTPUT_JS]

Defaults:
    EXAMPLES_DIR = examples/
    OUTPUT_JS    = data.js
"""

import sys
import os
import re
import json
import xml.etree.ElementTree as ET
from pathlib import Path

ALTO_NS = "http://www.loc.gov/standards/alto/ns-v4#"

IMAGE_EXTS = [".jpg", ".jpeg", ".JPG", ".JPEG", ".png", ".PNG", ".tif", ".tiff", ".TIF", ".TIFF"]


def find_image(xml_path: Path, folder: Path) -> str | None:
    stem = xml_path.stem
    for ext in IMAGE_EXTS:
        candidate = folder / (stem + ext)
        if candidate.exists():
            return str(candidate)
    return None


def parse_alto(xml_path: Path, image_path: str) -> dict:
    tree = ET.parse(xml_path)
    root = tree.getroot()

    def tag(name):
        return f"{{{ALTO_NS}}}{name}"

    # Build tag-id → label map from <Tags>
    tag_label = {}
    for other_tag in root.iter(tag("OtherTag")):
        tid = other_tag.get("ID")
        label = other_tag.get("LABEL")
        if tid and label:
            tag_label[tid] = label

    # Get page dimensions
    page_el = root.find(f".//{tag('Page')}")
    width = int(page_el.get("WIDTH", 0)) if page_el is not None else 0
    height = int(page_el.get("HEIGHT", 0)) if page_el is not None else 0

    # Get source filename for the title field (fallback to stem)
    src_el = root.find(f".//{tag('fileName')}")
    source_name = src_el.text.strip() if src_el is not None and src_el.text else xml_path.stem

    zones = []
    for tb in root.iter(tag("TextBlock")):
        tid = tb.get("ID", "")
        tagrefs = tb.get("TAGREFS", "")
        hpos = int(tb.get("HPOS", 0))
        vpos = int(tb.get("VPOS", 0))
        w = int(tb.get("WIDTH", 0))
        h = int(tb.get("HEIGHT", 0))

        # Resolve label from TAGREFS (space-separated list; use first match)
        label = None
        for ref in tagrefs.split():
            if ref in tag_label:
                label = tag_label[ref]
                break
        if label is None:
            label = "Unknown"

        # Get polygon points from <Shape><Polygon POINTS="...">
        poly_el = tb.find(f".//{tag('Polygon')}")
        if poly_el is not None:
            points = poly_el.get("POINTS", "")
        else:
            # Fall back to bounding-box corners
            points = f"{hpos} {vpos} {hpos+w} {vpos} {hpos+w} {vpos+h} {hpos} {vpos+h}"

        zones.append({
            "id": tid,
            "label": label,
            "points": points,
            "hpos": hpos,
            "vpos": vpos,
            "width": w,
            "height": h,
        })

    return {
        "id": xml_path.stem,
        "image": image_path,
        "width": width,
        "height": height,
        "title": source_name,
        "zones": zones,
    }


def main():
    examples_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("examples")
    output_js = Path(sys.argv[2]) if len(sys.argv) > 2 else Path("data.js")

    xml_files = sorted(examples_dir.glob("*.xml"))
    if not xml_files:
        print(f"No XML files found in {examples_dir}", file=sys.stderr)
        sys.exit(1)

    pages = []
    for xf in xml_files:
        img = find_image(xf, examples_dir)
        if img is None:
            print(f"  WARNING: no image found for {xf.name}, skipping", file=sys.stderr)
            continue
        # Make image path relative to output_js location
        try:
            rel = os.path.relpath(img, output_js.parent)
        except ValueError:
            rel = img
        page = parse_alto(xf, rel.replace("\\", "/"))
        pages.append(page)
        print(f"  {xf.name}  →  {len(page['zones'])} zones")

    js = "// Auto-generated by generate.py — do not edit manually.\n"
    js += "window.PAGES = " + json.dumps(pages, indent=2, ensure_ascii=False) + ";\n"

    output_js.write_text(js, encoding="utf-8")
    print(f"\nWrote {len(pages)} page(s) to {output_js}")


if __name__ == "__main__":
    main()
